#ifndef DISCOVERY_H
#define DISCOVERY_H

#define CONFIG_DISCOVERY_SOCKET_CREATION_INTERVAL_MS 100
#define CONFIG_DISCOVERY_PORT 5000
#define CONFIG_DISCOVERY_RECEIVING_BUFFER_SIZE 1500
#define CONFIG_DISCOVERY_TASK_STACK_SIZE 4096
#define CONFIG_DISCOVERY_TASK_PRIORITY 2

void initializeDiscovery();
void startDiscovery();

#endif
